const ActionTypes = {
    USERNAME: 'USERNAME',
    CURRENTUSER: 'CURRENTUSER',
    ALLUSERS: 'ALLUSERS',
    CHANGERECPUID: 'CHANGERECPUID',
    USER_LOGOUT: 'USER_LOGOUT',
    ALL_STUDENTS: 'ALL_STUDENTS',
    ALL_COMPANY_USERS: 'ALL_COMPANY_USERS',
    APPLIED_STUDENTS: 'APPLIED_STUDENTS',
    APPLIED_COMPANIES: 'APPLIED_COMPANIES'
}

export default ActionTypes;
