const ActionTypes = {
    USERNAME: 'USERNAME',
    CURRENTUSER: 'CURRENTUSER',
    ALLUSERS: 'ALLUSERS',
    CHANGERECPUID: 'CHANGERECPUID',
    USER_LOGOUT: 'USER_LOGOUT',
    UPDATE_MESSAGE: 'UPDATE_MESSAGE',
    UPDATE_RECIPIENT_MESSAGE: 'UPDATE_RECIPIENT_MESSAGE',
    EDIT_TIMER: 'EDIT_TIMER',
    EDIT_BOOLEAN: 'EDIT_BOOLEAN',
    CURRENT_MESSAGE_ADDRESS: 'CURRENT_MESSAGE_ADDRESS',
    ALL_MESSAGE_ADDRESSES: 'ALL_MESSAGE_ADDRESSES',
    ALL_RECIPIENT_MESSAGE_ADDRESSES: 'ALL_RECIPIENT_MESSAGE_ADDRESSES',
    CHANGE_REC_NAME: 'CHANGE_REC_NAME'
}

export default ActionTypes;
